
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package dev.xlonia.ostenbotanics.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import dev.xlonia.ostenbotanics.block.TswasjeskancaBlock;
import dev.xlonia.ostenbotanics.block.RhododendronBlock;
import dev.xlonia.ostenbotanics.block.ReimuhanaBlock;
import dev.xlonia.ostenbotanics.block.RapseedBlock;
import dev.xlonia.ostenbotanics.block.QeszwojcaBlock;
import dev.xlonia.ostenbotanics.block.PearSaplingBlock;
import dev.xlonia.ostenbotanics.block.PeachWoodBlock;
import dev.xlonia.ostenbotanics.block.PeachStairsBlock;
import dev.xlonia.ostenbotanics.block.PeachSlabBlock;
import dev.xlonia.ostenbotanics.block.PeachSaplingBlock;
import dev.xlonia.ostenbotanics.block.PeachPressurePlateBlock;
import dev.xlonia.ostenbotanics.block.PeachPlanksBlock;
import dev.xlonia.ostenbotanics.block.PeachLogBlock;
import dev.xlonia.ostenbotanics.block.PeachLeavesBlock;
import dev.xlonia.ostenbotanics.block.PeachFenceGateBlock;
import dev.xlonia.ostenbotanics.block.PeachFenceBlock;
import dev.xlonia.ostenbotanics.block.PeachButtonBlock;
import dev.xlonia.ostenbotanics.block.PalefloraBlock;
import dev.xlonia.ostenbotanics.block.OsmanthusSaplingBlock;
import dev.xlonia.ostenbotanics.block.MopemopeBlock;
import dev.xlonia.ostenbotanics.block.Maplepiles2Block;
import dev.xlonia.ostenbotanics.block.Maplepiles1Block;
import dev.xlonia.ostenbotanics.block.Maplepiles0Block;
import dev.xlonia.ostenbotanics.block.MapleWoodBlock;
import dev.xlonia.ostenbotanics.block.MapleStairsBlock;
import dev.xlonia.ostenbotanics.block.MapleSlabBlock;
import dev.xlonia.ostenbotanics.block.MapleSaplingBlock;
import dev.xlonia.ostenbotanics.block.MaplePressurePlateBlock;
import dev.xlonia.ostenbotanics.block.MaplePlanksBlock;
import dev.xlonia.ostenbotanics.block.MapleLogBlock;
import dev.xlonia.ostenbotanics.block.MapleFenceGateBlock;
import dev.xlonia.ostenbotanics.block.MapleFenceBlock;
import dev.xlonia.ostenbotanics.block.MapleButtonBlock;
import dev.xlonia.ostenbotanics.block.MagnoliusSaplingBlock;
import dev.xlonia.ostenbotanics.block.LycorisBlock;
import dev.xlonia.ostenbotanics.block.LotusBlock;
import dev.xlonia.ostenbotanics.block.LiquoriceBlock;
import dev.xlonia.ostenbotanics.block.LilyWhiteszBlock;
import dev.xlonia.ostenbotanics.block.LilyPinkszBlock;
import dev.xlonia.ostenbotanics.block.LeavesPearBlock;
import dev.xlonia.ostenbotanics.block.LeavesOsmanthusBlock;
import dev.xlonia.ostenbotanics.block.LeavesMapleBlock;
import dev.xlonia.ostenbotanics.block.LeavesMagnoliusBlock;
import dev.xlonia.ostenbotanics.block.LeavesHibiscusBlock;
import dev.xlonia.ostenbotanics.block.LeavesArmeniacusBlock;
import dev.xlonia.ostenbotanics.block.LaurWoodBlock;
import dev.xlonia.ostenbotanics.block.LaurStairsBlock;
import dev.xlonia.ostenbotanics.block.LaurSlabBlock;
import dev.xlonia.ostenbotanics.block.LaurSaplingBlock;
import dev.xlonia.ostenbotanics.block.LaurPressurePlateBlock;
import dev.xlonia.ostenbotanics.block.LaurPlanksBlock;
import dev.xlonia.ostenbotanics.block.LaurLogBlock;
import dev.xlonia.ostenbotanics.block.LaurLeavesBlock;
import dev.xlonia.ostenbotanics.block.LaurFenceGateBlock;
import dev.xlonia.ostenbotanics.block.LaurFenceBlock;
import dev.xlonia.ostenbotanics.block.LaurButtonBlock;
import dev.xlonia.ostenbotanics.block.JasmineBlock;
import dev.xlonia.ostenbotanics.block.HibiscusUtsomyBlock;
import dev.xlonia.ostenbotanics.block.HibiscusBlock;
import dev.xlonia.ostenbotanics.block.GinkgoWoodBlock;
import dev.xlonia.ostenbotanics.block.GinkgoStairsBlock;
import dev.xlonia.ostenbotanics.block.GinkgoSlabBlock;
import dev.xlonia.ostenbotanics.block.GinkgoSaplingBlock;
import dev.xlonia.ostenbotanics.block.GinkgoPressurePlateBlock;
import dev.xlonia.ostenbotanics.block.GinkgoPlanksBlock;
import dev.xlonia.ostenbotanics.block.GinkgoLogBlock;
import dev.xlonia.ostenbotanics.block.GinkgoLeavesBlock;
import dev.xlonia.ostenbotanics.block.GinkgoFenceGateBlock;
import dev.xlonia.ostenbotanics.block.GinkgoFenceBlock;
import dev.xlonia.ostenbotanics.block.GinkgoButtonBlock;
import dev.xlonia.ostenbotanics.block.GardeniaBlock;
import dev.xlonia.ostenbotanics.block.FallenMapleBlock;
import dev.xlonia.ostenbotanics.block.FallenMaple2Block;
import dev.xlonia.ostenbotanics.block.FallenMaple0Block;
import dev.xlonia.ostenbotanics.block.CameliaBlock;
import dev.xlonia.ostenbotanics.block.ArmeniacusSaplingBlock;
import dev.xlonia.ostenbotanics.block.ApricotWoodBlock;
import dev.xlonia.ostenbotanics.block.ApricotStairsBlock;
import dev.xlonia.ostenbotanics.block.ApricotSlabBlock;
import dev.xlonia.ostenbotanics.block.ApricotSaplingBlock;
import dev.xlonia.ostenbotanics.block.ApricotPressurePlateBlock;
import dev.xlonia.ostenbotanics.block.ApricotPlanksBlock;
import dev.xlonia.ostenbotanics.block.ApricotLogBlock;
import dev.xlonia.ostenbotanics.block.ApricotLeavesBlock;
import dev.xlonia.ostenbotanics.block.ApricotFenceGateBlock;
import dev.xlonia.ostenbotanics.block.ApricotFenceBlock;
import dev.xlonia.ostenbotanics.block.ApricotButtonBlock;
import dev.xlonia.ostenbotanics.OstenBotanicsMod;

public class OstenBotanicsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, OstenBotanicsMod.MODID);
	public static final RegistryObject<Block> LEAVES_OSMANTHUS = REGISTRY.register("leaves_osmanthus", () -> new LeavesOsmanthusBlock());
	public static final RegistryObject<Block> OSMANTHUS_SAPLING = REGISTRY.register("osmanthus_sapling", () -> new OsmanthusSaplingBlock());
	public static final RegistryObject<Block> GARDENIA = REGISTRY.register("gardenia", () -> new GardeniaBlock());
	public static final RegistryObject<Block> HIBISCUS = REGISTRY.register("hibiscus", () -> new HibiscusBlock());
	public static final RegistryObject<Block> LEAVES_HIBISCUS = REGISTRY.register("leaves_hibiscus", () -> new LeavesHibiscusBlock());
	public static final RegistryObject<Block> HIBISCUS_UTSOMY = REGISTRY.register("hibiscus_utsomy", () -> new HibiscusUtsomyBlock());
	public static final RegistryObject<Block> RHODODENDRON = REGISTRY.register("rhododendron", () -> new RhododendronBlock());
	public static final RegistryObject<Block> LEAVES_ARMENIACUS = REGISTRY.register("leaves_armeniacus", () -> new LeavesArmeniacusBlock());
	public static final RegistryObject<Block> ARMENIACUS_SAPLING = REGISTRY.register("armeniacus_sapling", () -> new ArmeniacusSaplingBlock());
	public static final RegistryObject<Block> LEAVES_MAGNOLIUS = REGISTRY.register("leaves_magnolius", () -> new LeavesMagnoliusBlock());
	public static final RegistryObject<Block> RAPSEED = REGISTRY.register("rapseed", () -> new RapseedBlock());
	public static final RegistryObject<Block> LOTUS = REGISTRY.register("lotus", () -> new LotusBlock());
	public static final RegistryObject<Block> LEAVES_PEAR = REGISTRY.register("leaves_pear", () -> new LeavesPearBlock());
	public static final RegistryObject<Block> CAMELIA = REGISTRY.register("camelia", () -> new CameliaBlock());
	public static final RegistryObject<Block> PEAR_SAPLING = REGISTRY.register("pear_sapling", () -> new PearSaplingBlock());
	public static final RegistryObject<Block> MAPLE_SAPLING = REGISTRY.register("maple_sapling", () -> new MapleSaplingBlock());
	public static final RegistryObject<Block> LILY_PINKSZ = REGISTRY.register("lily_pinksz", () -> new LilyPinkszBlock());
	public static final RegistryObject<Block> MOPEMOPE = REGISTRY.register("mopemope", () -> new MopemopeBlock());
	public static final RegistryObject<Block> LILY_WHITESZ = REGISTRY.register("lily_whitesz", () -> new LilyWhiteszBlock());
	public static final RegistryObject<Block> JASMINE = REGISTRY.register("jasmine", () -> new JasmineBlock());
	public static final RegistryObject<Block> LIQUORICE = REGISTRY.register("liquorice", () -> new LiquoriceBlock());
	public static final RegistryObject<Block> MAPLE_WOOD = REGISTRY.register("maple_wood", () -> new MapleWoodBlock());
	public static final RegistryObject<Block> MAPLE_LOG = REGISTRY.register("maple_log", () -> new MapleLogBlock());
	public static final RegistryObject<Block> MAPLE_PLANKS = REGISTRY.register("maple_planks", () -> new MaplePlanksBlock());
	public static final RegistryObject<Block> MAPLE_STAIRS = REGISTRY.register("maple_stairs", () -> new MapleStairsBlock());
	public static final RegistryObject<Block> MAPLE_SLAB = REGISTRY.register("maple_slab", () -> new MapleSlabBlock());
	public static final RegistryObject<Block> MAPLE_FENCE = REGISTRY.register("maple_fence", () -> new MapleFenceBlock());
	public static final RegistryObject<Block> MAPLE_FENCE_GATE = REGISTRY.register("maple_fence_gate", () -> new MapleFenceGateBlock());
	public static final RegistryObject<Block> MAPLE_PRESSURE_PLATE = REGISTRY.register("maple_pressure_plate", () -> new MaplePressurePlateBlock());
	public static final RegistryObject<Block> MAPLE_BUTTON = REGISTRY.register("maple_button", () -> new MapleButtonBlock());
	public static final RegistryObject<Block> LEAVES_MAPLE = REGISTRY.register("leaves_maple", () -> new LeavesMapleBlock());
	public static final RegistryObject<Block> GINKGO_WOOD = REGISTRY.register("ginkgo_wood", () -> new GinkgoWoodBlock());
	public static final RegistryObject<Block> GINKGO_LOG = REGISTRY.register("ginkgo_log", () -> new GinkgoLogBlock());
	public static final RegistryObject<Block> GINKGO_PLANKS = REGISTRY.register("ginkgo_planks", () -> new GinkgoPlanksBlock());
	public static final RegistryObject<Block> GINKGO_LEAVES = REGISTRY.register("ginkgo_leaves", () -> new GinkgoLeavesBlock());
	public static final RegistryObject<Block> GINKGO_STAIRS = REGISTRY.register("ginkgo_stairs", () -> new GinkgoStairsBlock());
	public static final RegistryObject<Block> GINKGO_SLAB = REGISTRY.register("ginkgo_slab", () -> new GinkgoSlabBlock());
	public static final RegistryObject<Block> GINKGO_FENCE = REGISTRY.register("ginkgo_fence", () -> new GinkgoFenceBlock());
	public static final RegistryObject<Block> GINKGO_FENCE_GATE = REGISTRY.register("ginkgo_fence_gate", () -> new GinkgoFenceGateBlock());
	public static final RegistryObject<Block> GINKGO_PRESSURE_PLATE = REGISTRY.register("ginkgo_pressure_plate", () -> new GinkgoPressurePlateBlock());
	public static final RegistryObject<Block> GINKGO_BUTTON = REGISTRY.register("ginkgo_button", () -> new GinkgoButtonBlock());
	public static final RegistryObject<Block> APRICOT_WOOD = REGISTRY.register("apricot_wood", () -> new ApricotWoodBlock());
	public static final RegistryObject<Block> APRICOT_LOG = REGISTRY.register("apricot_log", () -> new ApricotLogBlock());
	public static final RegistryObject<Block> APRICOT_PLANKS = REGISTRY.register("apricot_planks", () -> new ApricotPlanksBlock());
	public static final RegistryObject<Block> APRICOT_LEAVES = REGISTRY.register("apricot_leaves", () -> new ApricotLeavesBlock());
	public static final RegistryObject<Block> APRICOT_STAIRS = REGISTRY.register("apricot_stairs", () -> new ApricotStairsBlock());
	public static final RegistryObject<Block> APRICOT_SLAB = REGISTRY.register("apricot_slab", () -> new ApricotSlabBlock());
	public static final RegistryObject<Block> APRICOT_FENCE = REGISTRY.register("apricot_fence", () -> new ApricotFenceBlock());
	public static final RegistryObject<Block> APRICOT_FENCE_GATE = REGISTRY.register("apricot_fence_gate", () -> new ApricotFenceGateBlock());
	public static final RegistryObject<Block> APRICOT_PRESSURE_PLATE = REGISTRY.register("apricot_pressure_plate", () -> new ApricotPressurePlateBlock());
	public static final RegistryObject<Block> APRICOT_BUTTON = REGISTRY.register("apricot_button", () -> new ApricotButtonBlock());
	public static final RegistryObject<Block> PEACH_WOOD = REGISTRY.register("peach_wood", () -> new PeachWoodBlock());
	public static final RegistryObject<Block> PEACH_LOG = REGISTRY.register("peach_log", () -> new PeachLogBlock());
	public static final RegistryObject<Block> PEACH_PLANKS = REGISTRY.register("peach_planks", () -> new PeachPlanksBlock());
	public static final RegistryObject<Block> PEACH_LEAVES = REGISTRY.register("peach_leaves", () -> new PeachLeavesBlock());
	public static final RegistryObject<Block> PEACH_STAIRS = REGISTRY.register("peach_stairs", () -> new PeachStairsBlock());
	public static final RegistryObject<Block> PEACH_SLAB = REGISTRY.register("peach_slab", () -> new PeachSlabBlock());
	public static final RegistryObject<Block> PEACH_FENCE = REGISTRY.register("peach_fence", () -> new PeachFenceBlock());
	public static final RegistryObject<Block> PEACH_FENCE_GATE = REGISTRY.register("peach_fence_gate", () -> new PeachFenceGateBlock());
	public static final RegistryObject<Block> PEACH_PRESSURE_PLATE = REGISTRY.register("peach_pressure_plate", () -> new PeachPressurePlateBlock());
	public static final RegistryObject<Block> PEACH_BUTTON = REGISTRY.register("peach_button", () -> new PeachButtonBlock());
	public static final RegistryObject<Block> LAUR_WOOD = REGISTRY.register("laur_wood", () -> new LaurWoodBlock());
	public static final RegistryObject<Block> LAUR_LOG = REGISTRY.register("laur_log", () -> new LaurLogBlock());
	public static final RegistryObject<Block> LAUR_PLANKS = REGISTRY.register("laur_planks", () -> new LaurPlanksBlock());
	public static final RegistryObject<Block> LAUR_LEAVES = REGISTRY.register("laur_leaves", () -> new LaurLeavesBlock());
	public static final RegistryObject<Block> LAUR_STAIRS = REGISTRY.register("laur_stairs", () -> new LaurStairsBlock());
	public static final RegistryObject<Block> LAUR_SLAB = REGISTRY.register("laur_slab", () -> new LaurSlabBlock());
	public static final RegistryObject<Block> LAUR_FENCE = REGISTRY.register("laur_fence", () -> new LaurFenceBlock());
	public static final RegistryObject<Block> LAUR_FENCE_GATE = REGISTRY.register("laur_fence_gate", () -> new LaurFenceGateBlock());
	public static final RegistryObject<Block> LAUR_PRESSURE_PLATE = REGISTRY.register("laur_pressure_plate", () -> new LaurPressurePlateBlock());
	public static final RegistryObject<Block> LAUR_BUTTON = REGISTRY.register("laur_button", () -> new LaurButtonBlock());
	public static final RegistryObject<Block> FALLEN_MAPLE = REGISTRY.register("fallen_maple", () -> new FallenMapleBlock());
	public static final RegistryObject<Block> FALLEN_MAPLE_2 = REGISTRY.register("fallen_maple_2", () -> new FallenMaple2Block());
	public static final RegistryObject<Block> REIMUHANA = REGISTRY.register("reimuhana", () -> new ReimuhanaBlock());
	public static final RegistryObject<Block> PALEFLORA = REGISTRY.register("paleflora", () -> new PalefloraBlock());
	public static final RegistryObject<Block> TSWASJESKANCA = REGISTRY.register("tswasjeskanca", () -> new TswasjeskancaBlock());
	public static final RegistryObject<Block> QESZWOJCA = REGISTRY.register("qeszwojca", () -> new QeszwojcaBlock());
	public static final RegistryObject<Block> MAPLEPILES_0 = REGISTRY.register("maplepiles_0", () -> new Maplepiles0Block());
	public static final RegistryObject<Block> MAPLEPILES_1 = REGISTRY.register("maplepiles_1", () -> new Maplepiles1Block());
	public static final RegistryObject<Block> MAPLEPILES_2 = REGISTRY.register("maplepiles_2", () -> new Maplepiles2Block());
	public static final RegistryObject<Block> FALLEN_MAPLE_0 = REGISTRY.register("fallen_maple_0", () -> new FallenMaple0Block());
	public static final RegistryObject<Block> APRICOT_SAPLING = REGISTRY.register("apricot_sapling", () -> new ApricotSaplingBlock());
	public static final RegistryObject<Block> GINKGO_SAPLING = REGISTRY.register("ginkgo_sapling", () -> new GinkgoSaplingBlock());
	public static final RegistryObject<Block> PEACH_SAPLING = REGISTRY.register("peach_sapling", () -> new PeachSaplingBlock());
	public static final RegistryObject<Block> LYCORIS = REGISTRY.register("lycoris", () -> new LycorisBlock());
	public static final RegistryObject<Block> LAUR_SAPLING = REGISTRY.register("laur_sapling", () -> new LaurSaplingBlock());
	public static final RegistryObject<Block> MAGNOLIUS_SAPLING = REGISTRY.register("magnolius_sapling", () -> new MagnoliusSaplingBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
